version: "3.9"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env.db
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 3s
      retries: 3
  cron:
    platform: linux/x86_64
    build:
      context: ./cron
      dockerfile: Dockerfile-dev
    container_name: cron
    image: cron
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    env_file:
      - .env.db
    networks:
      - app-network
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./cron/src
        target: /src
    depends_on:
      postgres2:
        condition: service_healthy

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
