version: "3.9"

services:
  cron:
    build:
      context: ./cron
      dockerfile: Dockerfile-dev
    container_name: cron
    image: cron
    restart: always
    env_file:
      - .env.db
      - .env.cron
    networks:
      - app-network
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./cron/src
        target: /app/src
      - type: bind
        source: ./cron/prisma
        target: /app/prisma

networks:
  app-network:
    driver: bridge
