version: "3.9"

services:
  cron:
    platform: linux/x86_64
    build:
      context: ./cron
      dockerfile: Dockerfile
    container_name: cron
    image: cron
    restart: always
    env_file:
      - .env.db
    networks:
      - app-network
    ports:
      - "3000:3000"

networks:
  app-network:
    driver: bridge
