version: "3.9"

services:
  cat_catalogue:
    build:
      context: ./cat_catalogue
      dockerfile: Dockerfile-dev
    container_name: cat_catalogue
    restart: unless-stopped
    env_file:
      - .env.vite
    ports:
      - "3210:3210"
    volumes:
      - type: bind
        source: ./cat_catalogue/src
        target: /app/src
