version: "3.9"

services:
  cat_catalogue:
    build:
      context: ./cat_catalogue
      dockerfile: Dockerfile
    container_name: cat_catalogue
    restart: unless-stopped
    env_file:
      - .env.vite
    ports:
      - "3210:80"
