FROM node:slim as base

WORKDIR /app

# Add package file
COPY package*.json ./

# Install deps
RUN npm ci

# Copy source
COPY src ./src
COPY tsconfig.json ./tsconfig.json

# Expose main port
EXPOSE 3000

CMD ["npm", "run", "dev"]
