FROM node:slim as base
RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app

# Add package file
COPY package*.json ./

# Install deps
RUN npm ci

# Copy source
COPY src ./src
COPY prisma ./prisma

COPY tsconfig.json ./tsconfig.json

# Expose main port
EXPOSE 3000

CMD ["npm", "run", "dev"]
